<?php

namespace App\Document\Areabrick;

use Pimcore\Model\DataObject\Skill;
use Pimcore\Model\Document\Editable\Area\Info;

class Skills extends AbstractAreabrick
{
    /**
     * {@inheritdoc}
     */
    public function getName(): string
    {
        return 'nos skills';
    }

    /**
     * @throws \Exception
     */
    public function action(Info $info)
    {
        $info->setParams(['skills' => Skill::getList()->getData()]);
        return parent::action($info); // TODO: Change the autogenerated stub
    }

}
